# Generated by Django 2.0.1 on 2018-01-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='party',
            name='content3',
        ),
    ]
