# Generated by Django 2.0.1 on 2018-10-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
