# Generated by Django 2.0.1 on 2018-01-11 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_auto_20180111_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='content1',
        ),
        migrations.AddField(
            model_name='party',
            name='description',
            field=models.CharField(default='Party description', max_length=140),
        ),
        migrations.AddField(
            model_name='party',
            name='party_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='title',
            field=models.CharField(default='A party', max_length=140),
        ),
        migrations.AddField(
            model_name='party',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
