# Generated by Django 2.0.1 on 2018-10-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_auto_20181003_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='twitch_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
