# Generated by Django 2.0.1 on 2018-01-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_auto_20180111_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.CharField(default='Party description', max_length=280),
        ),
    ]
