# Generated by Django 2.0.1 on 2018-01-12 12:50

from django.db import migrations, models
import parties.models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_auto_20180111_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='title',
            field=models.CharField(max_length=140, validators=[parties.models.validate_title]),
        ),
    ]
