# Generated by Django 2.0.1 on 2018-11-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_party_is_private_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Lottery'), (2, 'Bid'), (3, 'Buy'), (4, 'Queue')], default=1),
        ),
    ]
