# Generated by Django 2.0.1 on 2018-11-17 17:12

from django.db import migrations, models
import parties.validators


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_auto_20181105_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.CharField(blank=True, max_length=280, validators=[parties.validators.validate_profanity]),
        ),
        migrations.AlterField(
            model_name='party',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Lottery'), (2, 'Bid'), (3, 'Buy'), (4, 'Queue')], default=4),
        ),
        migrations.AlterField(
            model_name='party',
            name='title',
            field=models.CharField(blank=True, max_length=140, validators=[parties.validators.validate_title, parties.validators.validate_profanity]),
        ),
    ]
