# Generated by Django 2.0.1 on 2018-01-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_auto_20180112_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['-time_created']},
        ),
    ]
