# Generated by Django 2.0.1 on 2019-01-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_auto_20181117_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='streamlabs_notifs',
            field=models.BooleanField(default=False),
        ),
    ]
