# Generated by Django 2.0.1 on 2018-01-19 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0008_auto_20180117_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited', to=settings.AUTH_USER_MODEL),
        ),
    ]
