# Generated by Django 2.0.1 on 2019-01-31 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0009_party_streamlabs_notifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_priority_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='priority_joined',
            field=models.ManyToManyField(blank=True, related_name='priority_joined_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
