# Generated by Django 2.0.1 on 2018-01-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0009_party_favorited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='favorited',
            new_name='starred',
        ),
    ]
