# Generated by Django 2.0.1 on 2018-01-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0010_auto_20180119_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='thumbnail',
            field=models.ImageField(default='media/thumbnails/fortniteThumbnail.jpg', upload_to='thumbnails/%Y/%m/%d/'),
        ),
    ]
