# Generated by Django 2.0.1 on 2019-05-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0010_auto_20190131_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='total_joins',
            field=models.IntegerField(default=0),
        ),
    ]
