# Generated by Django 2.0.1 on 2018-01-31 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0011_party_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='starred',
            field=models.ManyToManyField(blank=True, related_name='starred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/%Y/%m/%d/'),
        ),
    ]
