# Generated by Django 2.0.1 on 2019-05-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0011_party_total_joins'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='bs_sent',
            field=models.BooleanField(default=False),
        ),
    ]
