# Generated by Django 2.0.1 on 2018-01-31 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0012_auto_20180131_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='starred',
            field=models.ManyToManyField(blank=True, related_name='starred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
