# Generated by Django 2.0.1 on 2018-02-14 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0013_auto_20180131_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='joined',
            field=models.ManyToManyField(blank=True, related_name='joined_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
