# Generated by Django 2.0.1 on 2018-03-01 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0014_party_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='task_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='party',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='won_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
