# Generated by Django 2.0.1 on 2018-04-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0016_party_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='event_type',
            field=models.CharField(choices=[('EN', 'Entry'), ('BD', 'BID'), ('BY', 'BUY')], default='EN', max_length=2),
        ),
    ]
