# Generated by Django 2.0.1 on 2018-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0017_party_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='event_type',
            field=models.CharField(choices=[('DR', 'Drawing'), ('BD', 'Bid'), ('BY', 'Buy')], default='DR', max_length=2),
        ),
    ]
