# Generated by Django 2.0.1 on 2018-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0018_auto_20180419_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='event_type',
            field=models.CharField(choices=[('Drawing', 'Drawing'), ('Bid', 'Bid'), ('Buy', 'Buy')], default='Drawing', max_length=10),
        ),
    ]
