# Generated by Django 2.0.1 on 2018-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0019_auto_20180419_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='event_type',
            field=models.CharField(choices=[('DR', 'Drawing'), ('BD', 'Bid'), ('BY', 'Buy')], default='DR', max_length=10),
        ),
    ]
