# Generated by Django 2.0.1 on 2018-04-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0020_auto_20180419_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Drawing'), (2, 'Bid'), (3, 'Buy')], default=1),
        ),
    ]
