# Generated by Django 2.0.1 on 2018-05-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0022_party_num_winners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='num_winners',
            new_name='num_possible_winners',
        ),
        migrations.AddField(
            model_name='party',
            name='num_curr_winners',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
