# Generated by Django 2.0.1 on 2018-05-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0024_party_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='minimum_bid',
            field=models.IntegerField(default=0),
        ),
    ]
