# Generated by Django 2.0.1 on 2018-05-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0025_party_minimum_bid'),
        ('parties', '0025_party_max_entrants'),
    ]

    operations = [
    ]
