# Generated by Django 2.0.1 on 2018-05-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0027_auto_20180522_1732'),
        ('parties', '0027_remove_party_num_curr_winners'),
    ]

    operations = [
    ]
