# Generated by Django 2.0.1 on 2018-05-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0029_auto_20180524_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Lottery'), (2, 'Bid'), (3, 'Buy')], default=1),
        ),
    ]
