# Generated by Django 2.0.1 on 2018-05-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstatistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsinfo',
            name='max_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
