# Generated by Django 2.0.1 on 2018-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstatistics', '0002_statisticsinfo_max_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsinfo',
            name='max_bid_event',
            field=models.IntegerField(default=0),
        ),
    ]
