# Generated by Django 2.0.1 on 2018-06-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstatistics', '0002_auto_20180607_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticsinfo',
            name='max_profit_event',
        ),
    ]
