# Generated by Django 2.0.1 on 2018-06-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('userstatistics', '0003_remove_statisticsinfo_max_profit_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsinfo',
            name='max_profit_event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parties.Party'),
        ),
    ]
