# Generated by Django 2.0.1 on 2018-10-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181003_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
