# Generated by Django 2.0.1 on 2018-06-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180207_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='new_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
