# Generated by Django 2.0.1 on 2018-11-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181017_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_auth_token',
            field=models.CharField(blank=True, default='keyaut', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitch_OAuth_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitch_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitch_refresh_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
