# Generated by Django 2.0.1 on 2018-12-15 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_userprofile_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referred_list',
            field=models.ManyToManyField(blank=True, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
