# Generated by Django 2.0.1 on 2019-01-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_referred_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='streamlabs_access_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streamlabs_refresh_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
