# Generated by Django 2.0.1 on 2018-05-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0023_auto_20180508_1503'),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='party',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='parties.Party'),
            preserve_default=False,
        ),
    ]
