# Generated by Django 2.0.1 on 2018-06-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20180607_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_list', to='parties.Party'),
        ),
    ]
