# Generated by Django 2.0.1 on 2018-05-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20180511_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='party',
            field=models.IntegerField(default=0),
        ),
    ]
