# Generated by Django 2.0.1 on 2018-05-25 15:00

import bids.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20180515_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[bids.validators.validate_bid_amount]),
        ),
    ]
