# Generated by Django 2.0.1 on 2018-05-25 16:22

import bids.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_auto_20180525_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.IntegerField(default=0, validators=[bids.validators.validate_bid_amount]),
        ),
    ]
