# Generated by Django 2.0.1 on 2018-09-14 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('time_requested', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=280)),
                ('payment_info', models.CharField(max_length=40)),
                ('is_paid', models.BooleanField(default=False)),
                ('payout_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
